### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by pingometer** [jkeyes/python-intercom#45]
I attempted to install this with pip in Python 3.4.0 and got this error:

Running setup.py (path:/tmp/pip_build_root/python-intercom/setup.py) egg_info for package python-intercom
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/python-intercom/setup.py", line 13, in <module>
        with file(os.path.join('intercom', 'intercom.py')) as init:
    NameError: name 'file' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_root/python-intercom/setup.py", line 13, in <module>
    with file(os.path.join('intercom', 'intercom.py')) as init:
NameError: name 'file' is not defined

It looks like "file" is no longer a built-in. Any plans to support Python 3?

**Comment by jkeyes** [comment]
@pingometer Yes I have plans to support Python 3. I'll update here when it's in place.

**Comment by jkeyes** [comment]
@pingometer The apiv2 branch now supports Python 3 (tested with 3.4.3).
