### ISSUE TITLE
Getting ValueError while iterating over users with User.all()

### ISSUE THREAD

**Issue by carter2422** [jkeyes/python-intercom#95]
While attempting to iterate over users with `User.all()` I'm getting a ValueError. 

Even something as simple as this fails:
```
for user in User.all():
    print(user)
```

**Full Traceback:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/six.py", line 535, in next
    return type(self).__next__(self)
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/intercom/collection_proxy.py", line 45, in __next__
    instance = self.collection_cls(**resource)
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/intercom/traits/api_resource.py", line 41, in __init__
    _self.from_dict(params)
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/intercom/traits/api_resource.py", line 67, in from_dict
    setattr(self, attribute, value)
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/intercom/traits/api_resource.py", line 94, in __setattr__
    value_to_set = FlatStore(value)
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/intercom/lib/flat_store.py", line 10, in __init__
    self.update(*args, **kwargs)
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/intercom/lib/flat_store.py", line 30, in update
    self[key] = other[key]
  File "/Users/jonathanwilliamson/Documents/Web/cgcookie/cgc-customer/venv/lib/python2.7/site-packages/intercom/lib/flat_store.py", line 18, in __setitem__
    "custom data only allows string and real number values")
ValueError: custom data only allows string and real number values
```

*Note: iterating over companies in the same fashion works just fine.* I'm using version 2.0beta of python-intercom as that's the latest one that seems to be available on PyPi.

**Comment by teeberg** [comment]
I think this is the same problem as in #92

**Comment by jkeyes** [comment]
@carter2422 Have you tried with version 2.0.0?
